import java.util.Scanner;
public class numberGuessGame {

       public static void guessingNumberGame() {   // method named: guessingNumbergame
           Scanner sc = new Scanner(System.in);  //create scanner object
           int number = 1 + (int) (100 * Math.random());  // generating random number
           int k = 10; // initialising k ie.: no.of turns given to player
           int i, guess; // declaring variables
           System.out.println("A number is choosen " + "Between 1 to 100" + " given 10 trials " + " guess them");
           for (i = 0; i < k; i++) {    // for loop for k number of times
               System.out.println("guess the number");
               guess = sc.nextInt(); // taking input of guess from user
               if (number == guess) {         // number is generated by system and guess is by user
                   System.out.println("congrats!!");
                   break;
               } else if (number > guess & i != k - 1) {    // if no is grt than user input also the turn is not over means i is still less than k meaning turn to guess is still left
                   System.out.println("the number is greater than " + guess);
               } else if (number < guess & i != k - 1) {  // if no is small than guess and i is less than k meaning the turn to guess is still left
                   System.out.println("the number is smaller than" + guess);
               }

               if (i != k) // turn is over {
                   System.out.println("you have exhausted " + k + "trials");
               System.out.println("the number was " + number);
           }
       }

        public static void main(String []args ){
            guessingNumberGame(); // calling the above method 
        }

}